name:                miso-plane
version:             0.1.0.0
license:             BSD3
category:            Web
build-type:          Simple
cabal-version:       >=1.10

executable client
  main-is: Main.hs
  hs-source-dirs: src
  other-modules:
    Constants
    Model
    Update
    View
  build-depends:
      base
    , containers
    , ghcjs-base
    , miso
    , random
    , text
    , time
    , transformers
  default-language:    Haskell2010
  default-extensions:  DataKinds DeriveGeneric OverloadedStrings TypeOperators TypeFamilies RecordWildCards NamedFieldPuns
  ghc-options:
    -Wall
    -Werror
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -fno-warn-missing-home-modules

test-suite tests
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  hs-source-dirs: test, src
  other-modules:
    Constants
    ConstantsSpec
    Model
    ModelSpec
    Update
    UpdateSpec
  build-depends:
      base
    , containers
    , hspec
    , hspec-discover
    , miso
    , random
  default-language:    Haskell2010
  default-extensions:  DataKinds DeriveGeneric OverloadedStrings TypeOperators TypeFamilies RecordWildCards NamedFieldPuns
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints